/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicebuilder;

import exercicebuilder.builder.ComputerBuilder;
import exercicebuilder.enumeration.ChipsetEnum;
import exercicebuilder.enumeration.ColorEnum;
import exercicebuilder.enumeration.DDRtypeEnum;

public class App {

    public static void main(String[] args) {

        Computer computer = new ComputerBuilder()
                .setMouse()
                .setColor(ColorEnum.RED)
                .setRgb(false)
                .setWired(true)
                .setWireLength(2.5f)
                .and()
                .setCentralProcessingUnit()
                .setChipset(ChipsetEnum.INTEL)
                .setFrequency(3.2f)
                .setCoreCount(8)
                .and()
                .addMemoryModule()
                .setDdrType(DDRtypeEnum.DDR2)
                .setFrequency(120f)
                .setMemory(8)
                .and()
                .addMemoryModule()
                .setDdrType(DDRtypeEnum.DDR3)
                .setFrequency(140f)
                .setMemory(8)
                .and()
                .build();

        System.out.println(computer.getMemoryModules().size());
    }
}
